spring.application.name=server
server.port=8083

spring.h2.console.enabled=true

server.tomcat.threads.max=2000
server.tomcat.accept-count=5000
server.tomcat.threads.min-spare=200

spring.datasource.url=jdbc:h2:mem:bankserverdb
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000